### ISSUE TITLE
Bug: @vectorize-io/opencode-hindsight@0.2.1 fails to load in OpenCode 1.16.2

### ISSUE THREAD

**Issue by marcusyoung** [vectorize-io/hindsight#2028]
### Bug Description

Plugin fails to load with error: `Plugin export is not a function:

```ERROR 2026-06-06T00:46:08 +1332ms service=plugin path=@vectorize-io/opencode-hindsight error=Plugin export is not a function failed to load plugin```

### Steps to Reproduce

1. Install/update to OpenCode 1.16.2
2. Add `@vectorize-io/opencode-hindsight@latest` to `opencode.json` plugins
3. Start OpenCode
4. Check logs for error

### Expected Behavior

Plugin loads successfully and registers `hindsight_recall`, `hindsight_retain`, `hindsight_reflect` tools

### Actual Behavior

Plugin fails to initialize. No tools are registered. 

## Workaround

Downgrade to @vectorize-io/opencode-hindsight@0.2.0, which works fine with OpenCode 1.16.2

### Version

- OpenCode: 1.16.2 - @vectorize-io/opencode-hindsight: 0.2.1 (released 2026-06-05) - OS: Windows

### LLM Provider

Other
