### PR TITLE
fix(hindsight-api-slim): bump opentelemetry-{api,sdk,instrumentation,exporter} floors so PrometheusMetricReader 0.62b1 doesn't crash startup

### LINKED ISSUE #1372: Daemon startup logs `MetricReader.__init__() got an unexpected keyword argument 'otel_component_type'` — `opentelemetry-sdk>=1.20.0` lower bound is too loose
## Summary

On a fresh `pip install hindsight-api-slim==0.5.6` (or `hindsight-all==0.5.6`) into a Python 3.11 venv, `hindsight-api` startup logs:

```
WARNING - root - Failed to initialize metrics: MetricReader.__init__() got an unexpected keyword argument 'otel_component_type'. Metrics will be disabled (using no-op collector).
```

Functionally Hindsight keeps running (the no-op collector kicks in), but the `/metrics` endpoint is silently empty for the rest of the process lifetime.

## Root cause

`hindsight-api-slim/pyproject.toml` declares:

```toml
"opentelemetry-api>=1.20.0",
"opentelemetry-sdk>=1.20.0",
"opentelemetry-instrumentation-fastapi>=0.41b0",
"opentelemetry-exporter-prometheus>=0.41b0",
"opentelemetry-exporter-otlp-proto-http>=1.20.0",
"opentelemetry-semantic-conventions>=0.41b0",
```

`pip` resolves the latest `opentelemetry-exporter-prometheus` (currently `0.62b1`), whose [`PrometheusMetricReader.__init__`](https://github.com/open-telemetry/opentelemetry-python/blob/v1.41.1/exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py#L137-L150) calls `super().__init__(..., otel_component_type=...)`. That keyword was added to `MetricReader.__init__` only in `opentelemetry-sdk` **v1.41.0** ([PR open-telemetry/opentelemetry-python#4970](https://github.com/open-telemetry/opentelemetry-python/pull/4970), released 2026-04-09).

If a project already had `opentelemetry-sdk<1.41` pinned by another transitive (or had it cached in the lockfile from before), the bump to `0.62b1` exporter-prometheus pulls in but sdk stays at `1.39.x`/`1.40.x`. `PrometheusMetricReader()` then explodes on `super().__init__(..., otel_component_type=…)`.

I confirmed:

- `v1.39.1` sdk: 0 occurrences of `otel_component_type` in `metrics/_internal/export/__init__.py`
- `v1.40.0` sdk: 0 occurrences
- `v1.41.0` sdk: 7 occurrences (kwarg added)
- `v1.41.1` sdk: 7 occurrences

## Repro

Python 3.11, fresh venv:

```bash
python -m venv /tmp/hs && source /tmp/hs/bin/activate
pip install --quiet hindsight-api==0.5.6 'opentelemetry-sdk<1.41'  # forces the broken combo
hindsight-api --port 9177 2>&1 | grep -i metric
# → WARNING - root - Failed to initialize metrics: MetricReader.__init__() got an unexpected keyword argument 'otel_component_type'.
```

In production we hit this without the artificial `<1.41` pin because the venv was built incrementally and the `opentelemetry-sdk` 1.39.1 wheel was already cached when 0.62b1 of exporter-prometheus landed.

## Suggested fix

Bump the floor of `opentelemetry-api` and `opentelemetry-sdk` in `hindsight-api-slim/pyproject.toml` to `>=1.41.0`, since the contemporary `opentelemetry-exporter-prometheus>=0.62b1` requires it. (Optionally also raise `instrumentation`/`semantic-conventions` floors to `>=0.62b1` for the same reason.)

PR with this minimal change incoming.

## Workaround for users on 0.5.6

```
pip install --upgrade 'opentelemetry-api>=1.41' 'opentelemetry-sdk>=1.41' \
                       'opentelemetry-semantic-conventions>=0.62b1' \
                       'opentelemetry-util-http>=0.62b1' \
                       'opentelemetry-instrumentation>=0.62b1' \
                       'opentelemetry-instrumentation-fastapi>=0.62b1' \
                       'opentelemetry-instrumentation-aiohttp-client>=0.62b1' \
                       'opentelemetry-exporter-otlp-proto-http>=1.41' \
                       'opentelemetry-exporter-prometheus>=0.62b1'
```
After this `Metrics initialized — available at /metrics endpoint` shows up cleanly on hindsight startup.

## Environment

- `hindsight-api-slim` 0.5.6, `hindsight-api` 0.5.6, `hindsight-all` 0.5.6, `hindsight-embed` 0.5.6
- Python 3.11.15, Debian 13 (trixie) ARM64
- Reproduces on x86_64 Linux too (same wheels)

### PR DESCRIPTION
**Pull request by nikolay-bratanov**
Fixes #1372.

## Why

`opentelemetry-exporter-prometheus 0.62b1` calls `MetricReader.__init__(otel_component_type=…)`, a kwarg that `opentelemetry-sdk` introduced only in **v1.41.0** ([open-telemetry/opentelemetry-python#4970](https://github.com/open-telemetry/opentelemetry-python/pull/4970), released 2026-04-09).

Verified by greping each tagged sdk:

| sdk version | `otel_component_type` occurrences in `metrics/_internal/export/__init__.py` |
|---|---|
| `v1.39.1` | 0 |
| `v1.40.0` | 0 |
| `v1.41.0` | 7 (kwarg added) |
| `v1.41.1` | 7 |

The previous floors in `hindsight-api-slim/pyproject.toml`:

```toml
"opentelemetry-api>=1.20.0",
"opentelemetry-sdk>=1.20.0",
"opentelemetry-instrumentation-fastapi>=0.41b0",
"opentelemetry-exporter-prometheus>=0.41b0",
"opentelemetry-exporter-otlp-proto-http>=1.20.0",
"opentelemetry-semantic-conventions>=0.41b0",
```

let pip happily resolve `opentelemetry-exporter-prometheus 0.62b1` (current latest) against a `1.39.x`/`1.40.x` sdk that was already cached in a venv/lockfile from before. `hindsight-api` then logs at startup:

```
WARNING - root - Failed to initialize metrics: MetricReader.__init__() got an unexpected keyword argument 'otel_component_type'. Metrics will be disabled (using no-op collector).
```

The daemon stays up (no-op collector kicks in) but `/metrics` is silently empty for the rest of the process lifetime.

## What

Bump all six otel-related deps to the matching `1.41.0` / `0.62b1` floor so pip's resolver keeps the otel ecosystem consistent:

```diff
-    "opentelemetry-api>=1.20.0",
-    "opentelemetry-sdk>=1.20.0",
-    "opentelemetry-instrumentation-fastapi>=0.41b0",
-    "opentelemetry-exporter-prometheus>=0.41b0",
-    "opentelemetry-exporter-otlp-proto-http>=1.20.0",
-    "opentelemetry-semantic-conventions>=0.41b0",
+    "opentelemetry-api>=1.41.0",
+    "opentelemetry-sdk>=1.41.0",
+    "opentelemetry-instrumentation-fastapi>=0.62b1",
+    "opentelemetry-exporter-prometheus>=0.62b1",
+    "opentelemetry-exporter-otlp-proto-http>=1.41.0",
+    "opentelemetry-semantic-conventions>=0.62b1",
```

## Verification

Reproduced locally with `hindsight-api-slim 0.5.6` + `opentelemetry-sdk==1.39.1` + `opentelemetry-exporter-prometheus==0.62b1`:

```
WARNING - root - Failed to initialize metrics: MetricReader.__init__() got an unexpected keyword argument 'otel_component_type'. Metrics will be disabled (using no-op collector).
```

After upgrading the entire otel stack to 1.41.1 / 0.62b1 (workaround documented in #1372), `hindsight-api` startup logs:

```
INFO - root - Metrics initialized - available at /metrics endpoint
```

— and the `/metrics` endpoint serves data normally. With this PR's floor bumps applied, every fresh install gets that working state by default.

## Risk

Strictly raising lower bounds. Anyone already on the broken combination gets a one-time pip resolver bump on next install; anyone already on `>=1.41`/`>=0.62b1` is unaffected. No code changes.

## Notes

- `mistralai 2.3.2` separately requires `opentelemetry-semantic-conventions<0.61,>=0.60b1`, which conflicts with this PR's `>=0.62b1` floor. In the venv where I verified, mistralai is only used for an optional provider so the conflict is a `pip check` warning rather than a runtime issue. If hindsight does end up needing mistralai imported on the hot path, that's a separate upstream pin to relax in `mistralai`.

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]
LGTM, thanks!
