### ISSUE TITLE
bug: bundled Grafana dashboards fail to load on Grafana < 8.3 ("Templating ... e.replace is not a function")

### ISSUE THREAD

**Issue by oldnicke** [vectorize-io/hindsight#3968]
## Bug Description

The three dashboards in `monitoring/grafana/dashboards/` are saved in the Grafana 10-era save-model format, and `hindsight-docs/docs/developer/monitoring.md` tells users to "Import these JSON files into your Grafana instance" without stating a minimum Grafana version. On an older Grafana (reproduced on **7.5.17**) the import succeeds but the dashboard is unusable: a red toast appears and no panel renders.

```
Templating
Template variable service failed  e.replace is not a function
```

(depending on the code path it also shows up as `Templating / Failed to upgrade legacy queries / e.replace is not a function`)

Two fields use shapes that only exist in Grafana >= 8.3/9:

1. Panel and variable `datasource` is an object ref (introduced by schemaVersion 33):
   ```json
   "datasource": { "type": "prometheus", "uid": "prometheus" }
   ```
2. The Prometheus query variable `query` is the variable-editor object:
   ```json
   "query": {
     "query": "label_values(hindsight_http_requests_total, tenant)",
     "refId": "PrometheusVariableQueryEditor-VariableQuery"
   }
   ```

The files declare `"schemaVersion": 38`. Grafana's `DashboardMigrator` only ever migrates **up**, so on a 7.5 instance no migration runs and both objects are handed to code that expects a string:

- `DatasourceSrv.get()` (v7.5.17, `public/app/features/plugins/datasource_srv.ts`):
  ```ts
  // Interpolation here is to support template variable in data source selection
  nameOrUid = this.templateSrv.replace(nameOrUid, scopedVars, variableInterpolation);
  ```
- Prometheus `metricFindQuery(query)` -> `this.templateSrv.replace(query, ...)`

`TemplateSrv.replace()` does `target.replace(...)`, so an object throws `TypeError: e.replace is not a function` and variable initialization aborts.

**Secondary issue:** `"uid": "prometheus"` is hardcoded. That uid only exists in the `grafana/otel-lgtm` image used by `scripts/dev/monitoring/docker-compose.yaml`. On any other Grafana instance the panels render `Datasource prometheus was not found`, so the dashboards are effectively dev-stack-only despite the docs presenting them as importable artifacts.

## Steps to Reproduce

1. Run Grafana 7.5.x with a Prometheus datasource whose uid is *not* `prometheus`
2. Dashboards -> Import -> paste `monitoring/grafana/dashboards/hindsight-api-service.json`
3. Open the imported dashboard

Same result for `hindsight-llm.json` and `hindsight-operations.json`.

## Expected Behavior

The dashboards import and populate on the Grafana versions the docs point users at, or `monitoring.md` documents a minimum supported Grafana version.

## Actual Behavior

`Templating / Template variable service failed / e.replace is not a function`; the `tenant` variable never initializes and all panels stay empty. With a differently-named Prometheus datasource, panels additionally report `Datasource prometheus was not found`.

## Suggested fix

A form that works on 7.5 through 12, since modern Grafana still accepts (and migrates) a string datasource and a legacy string variable query:

- `"datasource": "$datasource"` on every panel and on the variable, plus a `type: datasource` template variable:
  ```json
  {
    "current": {},
    "hide": 0,
    "includeAll": false,
    "label": "Data source",
    "multi": false,
    "name": "datasource",
    "options": [],
    "query": "prometheus",
    "refresh": 1,
    "regex": "",
    "skipUrlSync": false,
    "type": "datasource"
  }
  ```
  `"current": {}` makes Grafana auto-select any prometheus-type datasource, so `scripts/dev/monitoring` keeps working unchanged and users of other instances get a picker instead of editing JSON.
- Keep the variable query as the legacy string: `"query": "label_values(hindsight_http_requests_total, tenant)"`.

Two alternatives that look tempting but regress something:

- `${DS_PROMETHEUS}` + an `__inputs` block fixes UI import but breaks the file provisioning in `scripts/dev/monitoring` (provisioning does not substitute inputs).
- `"datasource": null` (org default) breaks the dev stack, because `grafana/otel-lgtm` marks no datasource as `isDefault`.

Remaining 7.5 gaps after that change are cosmetic only and silently ignored: `timeseries` `stacking` (8.0+), `custom.lineStyle` (8.x), `legend.showLegend` (9+).

Happy to open a PR with the change across the three dashboards if that direction looks right.

## Version

- Repo: `6e34d26` (dashboards unchanged for a while; affects all three files)
- Grafana: 7.5.17, Prometheus datasource
